# Generated by Django 5.1.1 on 2024-10-08 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Категории товаров')),
                ('description', models.CharField(default='Описание категории продуктов', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': ('Категория',),
                'verbose_name_plural': ('Категории',),
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(verbose_name='Общая стоимость заказа')),
                ('status', models.CharField(choices=[('Pending', 'В ожидании'), ('Shipped', 'Отправлен'), ('Delivered', 'Доставлен')], max_length=50, verbose_name='Статус заказа')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Время создания заказа')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Время последнего изменения статуса')),
            ],
            options={
                'verbose_name': ('Общая стоимость',),
                'verbose_name_plural': ('Общие стоимости',),
                'ordering': ['-total_price'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': ('Пользователь',),
                'verbose_name_plural': ('Пользователи',),
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('description', models.CharField(default='Описание продукта', max_length=255, verbose_name='Описание продукта')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='models_database.category', verbose_name='Категории товаров')),
            ],
            options={
                'verbose_name': ('Название продукта',),
                'verbose_name_plural': ('Названии продуктов',),
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='models_database.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='models_database.product', verbose_name='Название продукта')),
            ],
            options={
                'verbose_name': ('Количество',),
                'verbose_name_plural': ('Количество',),
                'ordering': ['quantity', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userprofile', serialize=False, to='models_database.user', verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': ('Профиль пользователя',),
                'verbose_name_plural': ('Профили пользователей',),
                'ordering': ['address'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='models_database.user', verbose_name='Пользователь'),
        ),
    ]
